# RELEASE
# Crea un release de todo el proyecto 
# Genera 2 archivos comprimidos para descargar alguno de los 2(zip) o (tar.gz)


name: ic_java_05012023
on: 
 push:
    branches: [ "master" ]
    tags:
      - "v*"
 pull_request:  
    branches: [ master]
    tags:
      - "v*"   
jobs:
    master_java:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - run: |
           echo "Paso1__________________________10012023"
           mkdir -p path/to/artifact
           pwd
           ls
          
        - run: echo hello > path/to/artifact/world.txt

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: path/to/artifact/world.txt
        
       
        - uses: actions/create-release@v1
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          with:
            tag_name: v.0.0.${{ github.run_number }}
            release_name: v.0.0.${{ github.run_number }}
            files: |
             world.txt
             *.txt
  

