name: ic_java_05012023
on: 
 push:
    branches: [ "master" ]
 pull_request:  
   branches: [ master]
jobs:
    master_java:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3 
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - run: dir
        - run: ls 
