name: ic_java_05012023
on: 
 push:
    branches: [ "master" ]
 pull_request:  
   branches: [ master]
jobs:
    master_java:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - run: |
           echo "Paso1__________________________10012023"
           mkdir -p path/to/artifact
           pwd
           ls
          
        - run: echo hello > path/to/artifact/world.txt

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: path/to/artifact/world.txt
        
       
        - uses: actions/create-release@v1
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            bump_version_scheme: minor
            tag_prefix: v
