name: ic_java_05012023
on: 
 push:
    branches: [ "master" ]
 pull_request:  
   branches: [ master]
jobs:
    master_java:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - run: |
           echo "Paso1__________________________"
           mkdir -p path/to/artifact
           pwd
           ls
          
        - run: echo hello > path/to/artifact/world.txt

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: path/to/artifact/world.txt
        - name: fin-Install dependencies
          run:  dotnet publish "${{ github.workspace }}/path/to/artifact/world.tx"     
