name: ic_java_05012023

on: 
  pull_request:  
    branches: [ master]
jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3 
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven  
      - run: dir
      - run: ls            
          
          
      
    
        
        
        
        

       

     
 
