name: ic_java_05012023
on: 
 push:
    branches: [ "master" ]
 pull_request:  
   branches: [ master]
jobs:
    master_java:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3 
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - run: dir
        - run: ls
        - run: cd target
        - run: dir
        - name: Step 1 - Create a temporary artifact downloads folder
          run: mkdir downloads
        
        - name: step 2 - Add artifacts to publish to the temp folder
          run: |
           cd downloads
           echo 'alpha'    > alpha.html
           echo 'bravo'    > bravo.html
           echo 'charlie'  > charlie.html
           cd ..
    
        - name: Step 3 - Use the Upload Artifact GitHub Action
          uses: actions/upload-artifact@v2
          with: 
           name: assets-for-download
           path: downloads
        - name: 4 fin
          run: |
           cd downloads
           pwd
           ls
